### ISSUE TITLE
Can't install from npm

### ISSUE THREAD

**Issue by vicmosin** [pathofdev/react-tag-input#1]
On macbook, once I add the dependency to project.json, it fails with:
```
2100 verbose stack TypeError: Cannot read property 'match' of undefined
2100 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
2100 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
2100 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12
2100 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2100 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
2100 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
2100 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2100 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
2100 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
2100 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
2100 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
2100 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
2100 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
2100 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
2100 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2100 verbose stack     at processImmediate (internal/timers.js:439:21)
2101 verbose cwd /Users/victormosin/Documents/Projects/Munchbot/frontend-distributor
2102 verbose Darwin 18.7.0
2103 verbose argv "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "--scripts-prepend-node-path=auto"
2104 verbose node v12.11.1
2105 verbose npm  v6.12.0
2106 error Cannot read property 'match' of undefined
```

Tried to remove node_modules folder and lock files -> no success. Any ideas?

**Comment by realfresh** [comment]
Hey, thanks for reporting. Turns out installing via NPM was broken, Yarn was fine. Seems there was something wrong with the package-lock.json file that was being published that caused the error you saw. Anyways, I fixed it up and published a new version 1.0.7. You should be able to install that with NPM fine. Let me know if you bump into the issue again.
